times = ("Flamengo", "Palmeiras", "São Paulo", "Santos", "Corinthians", "Vasco da Gama", "Fluminense", "Grêmio", "Internacional", "Atlético Mineiro", "Cruzeiro", "Botafogo", "Bahia", "Athletico Paranaense", "Coritiba", "Fortaleza", "Ceará", "Sport Recife", "Goiás", "Chapecoense")
print('-='*30)
print(f'Lista de times do BRASILEIRÃO: {times}')
print('-='*30)
print(f'os 5 primeiros são {times[0:5]}')
print('-='*30)
print(f'os 4 ultimos colocados são {times[-4:]}')
print('-='*30)
print(f'Os times em ordem alfaetica: {sorted(times)}')
print('-='*30)
print(f'Chapecoence ficou em {times.index("Chapecoense")+1}ª posição!')
print('-='*30)